version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   # Expose frontend on port 3000
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"   # Expose backend on port 8080
    environment:
      - NODE_ENV=production
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb       # Backend depends on MongoDB

  mongodb:
    image: mongo:4.4  # MongoDB version
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: myapp_db

volumes:
  mongo-data:
